# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Coverage

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install .[dev]

    - name: Run coverage
      run: |
        pytest --cov=./pkmodel --cov-report=xml --cov-branch
        cat coverage.xml
        
    - name: Lint with flake8
      run: |
        flake8 --max-line-length=120
    - name: Test with pytest
      run: |
        pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        files: coverage.xml
